project_name: pricking
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm'
      - goos: windows
        goarch: 'arm64'
    binary: '{{ .ProjectName }}'
    main: cmd/pricking/pricking.go

# https://goreleaser.com/customization/archive/
archives:
  - files:
      - "config"
      - "pricking-js-suite"
checksum:
  algorithm: sha256
