filter_type:
  - "text/html"
exclude_file:
  - ".jpg"
  - ".css"
  - ".png"
  - ".js"
  - ".ico"
  - ".svg"
  - ".gif"
  - ".jpeg"
  - ".woff"
  - ".tff"
static_dir: "./pricking-js-suite"
pricking_prefix_url: "/pricking_static_files"
listen_address: ":9999"
inject_body: "<script src='/pricking_static_files/static.js' type='module'></script>"
