filter_type:
  - "text/html"
exclude_file_types:
  - ".jpg"
  - ".css"
  - ".png"
  - ".js"
  - ".ico"
  - ".svg"
  - ".gif"
  - ".jpeg"
  - ".woff"
  - ".tff"
save_file_types:
  - "application/octet-stream"
  - "application/pdf"
plugins:
  username:
    enable: true
    path: "/get_users"
save_file_dir: "./tmp"
static_dir: "./pricking-js-suite"
pricking_prefix_url: "/pricking_static_files"
listen_address: ":9999"
inject_body: "<script src='/pricking_static_files/static.js' type='module'></script>"
