name: Release Go project

on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.17.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
      - name: Create Pricking JS Suite
        run: zip -q -r pricking-js-suite.zip ./pricking-js-suite
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pricking-js-suite.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
